version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"  
    depends_on:
      - db

volumes:
  pgdata: