version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Run schema at startup

volumes:
  pgdata:
